version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/hotel_bi
      - REDIS_URL=redis://redis:6379
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_URL=${AI_API_URL}
      - ENVIRONMENT=development
    volumes:
      - ../app:/app
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/hotel_bi
      - REDIS_URL=redis://redis:6379
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_URL=${AI_API_URL}
    volumes:
      - ../app:/app
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hotel_bi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_data:
  minio_data: 